
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//@author Elias Neto

public class Jbuscaproduto extends javax.swing.JDialog {
    
    Produto produto = null;
    List<Produto> lista;

    public Produto getProduto() { //getProduto feito para passar o produto encontrado para o form Jprodutos
        return produto;
    }
    
    public Jbuscaproduto(java.awt.Frame parent, boolean modal) { //CONSTRUTOR
        super(parent, modal);
        initComponents();
        regularColunas();   }
    
    private void preencherTabela(){
        DefaultTableModel model = new MeuModeloTabela();
        model.addColumn("Código ID");
        model.addColumn("Descrição");
        model.addColumn("Valor Unitário");
        model.addColumn("Quantidade em Estoque");
        lista.stream().map((c) -> new Object[]{
            c.getCodigo(),
            c.getDescricao(),
            c.getValorUnitario(),
            c.getQtde()}).forEach((linha) -> {
                model.addRow(linha);
            });
        tabela.setModel(model);
        regularColunas();    }
    
    private void regularColunas(){
        tabela.getColumnModel().getColumn(0).setPreferredWidth(55); //Regula a largura das colunas 0,1 e 3
        tabela.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(145);    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labelDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btCodigo = new javax.swing.JButton();
        btDescricao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        labelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCodigo.setText("Código:");
        getContentPane().add(labelCodigo);
        labelCodigo.setBounds(20, 20, 50, 30);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(73, 20, 70, 30);

        labelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDescricao.setText("Descrição:");
        getContentPane().add(labelDescricao);
        labelDescricao.setBounds(220, 20, 70, 30);
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(290, 20, 130, 30);

        btCodigo.setText("Buscar Código");
        btCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarCodigo(evt);
            }
        });
        getContentPane().add(btCodigo);
        btCodigo.setBounds(20, 60, 140, 26);

        btDescricao.setText("Buscar Descrição");
        btDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaDescricao(evt);
            }
        });
        getContentPane().add(btDescricao);
        btDescricao.setBounds(280, 60, 140, 26);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código ID", "Descrição", "Valor Unitário", "Quantidade em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarProduto(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 100, 440, 230);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dê clique-duplo no produto desejado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 330, 220, 30);

        setSize(new java.awt.Dimension(457, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void localizarCodigo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarCodigo
        // TODO add your handling code here:
        try{ //Adicionei esse Try, porque quando o usuario busca um ID não existeste, o programa da Erro.
            if(!txtCodigo.getText().equals(""))
            produto = Repositorio.localizarProduto(Integer.parseInt(txtCodigo.getText()));
            lista = new ArrayList<Produto>();
            lista.add(produto);
            preencherTabela();           
        }catch(java.lang.NullPointerException e){
            JOptionPane.showMessageDialog(this, "Erro na busca!");
        }        
    }//GEN-LAST:event_localizarCodigo

    private void buscaDescricao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaDescricao
        // TODO add your handling code here:
        lista = Repositorio.localizarProduto(txtDescricao.getText());
        preencherTabela();
    }//GEN-LAST:event_buscaDescricao

    private void selecionarProduto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarProduto
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){ // "SE" for clicado duas vezes:
            produto = lista.get(tabela.getSelectedRow());
            dispose();
        }
    }//GEN-LAST:event_selecionarProduto

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCodigo;
    private javax.swing.JButton btDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
