import javax.swing.JOptionPane;

//@author Elias Neto

public class Jprodutos extends javax.swing.JFrame {

    Produto produto = null;
    boolean inserindo = false; 
    
    public Jprodutos() {
        initComponents();
        ativarBotoes();
    }
    
    private void ativarBotoes(){ //Usado para controlar o uso dos botões da tela. É executado inicialmente ao abrir a janela
        btNovo.setEnabled(!txtCodigo.isEnabled());
        btAlterar.setEnabled(produto != null && !txtCodigo.isEnabled());
        btGravar.setEnabled(txtCodigo.isEnabled());
        btCancelar.setEnabled(txtCodigo.isEnabled());
        btBuscar.setEnabled(!txtCodigo.isEnabled());
        btExcluir.setEnabled(produto != null && !txtCodigo.isEnabled());
    }
    
    public void limparCampos(){ //Usado para deixar os campos de texto em branco
        txtCodigo.setText("");
        txtDescricao.setText("");
        txtQuantidade.setText("");
        txtValor.setText("");
    }
    
    private void ativacaoCampos(boolean status){
        txtCodigo.setEnabled(status);
        txtDescricao.setEnabled(status);
        txtQuantidade.setEnabled(status);
        txtValor.setEnabled(status);
        ativarBotoes();
    }
    
    private boolean validapreenchimento() {
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo Código é obrigatório");
            txtCodigo.requestFocus();
            return false;
        }
        if (txtDescricao.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo Descrição é obrigatório");
            txtDescricao.requestFocus();
            return false;
        }

        if (txtQuantidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo Quantidade é obrigatório");
            txtQuantidade.requestFocus();
            return false;
        }
        return true;
    }
    
    private void preenchercampos() {
        if (produto != null) {
            txtCodigo.setText(String.valueOf(produto.getCodigo()));
            txtDescricao.setText(produto.getDescricao());
            txtValor.setText(String.valueOf(produto.getValorUnitario()));
            txtQuantidade.setText(String.valueOf(produto.getQtde()));
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btGravar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo(evt);
            }
        });
        getContentPane().add(btNovo);
        btNovo.setBounds(10, 10, 62, 26);

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar(evt);
            }
        });
        getContentPane().add(btAlterar);
        btAlterar.setBounds(100, 10, 73, 26);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(190, 10, 73, 26);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });
        getContentPane().add(btBuscar);
        btBuscar.setBounds(390, 10, 75, 26);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 90, 30);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descrição:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 90, 30);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Quantidade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Valor unitário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 180, 100, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Opcional");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 90, 20);

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravar(evt);
            }
        });
        getContentPane().add(btGravar);
        btGravar.setBounds(270, 280, 72, 26);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(120, 280, 90, 26);

        txtCodigo.setEnabled(false);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(110, 60, 80, 30);

        txtDescricao.setEnabled(false);
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(110, 100, 180, 30);

        txtQuantidade.setEnabled(false);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(110, 140, 80, 30);

        txtValor.setEnabled(false);
        getContentPane().add(txtValor);
        txtValor.setBounds(110, 180, 80, 30);

        setSize(new java.awt.Dimension(492, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo
        // TODO add your handling code here:
        inserindo = true;
        limparCampos();
        ativacaoCampos(true);
        produto = new Produto();
        txtCodigo.requestFocus(); //Foca o campo de Codigo, deixando de prontidão para digitar.
    }//GEN-LAST:event_novo

    private void gravar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravar
        // TODO add your handling code here:
        if(!validapreenchimento()){ //verifica se os campos estão todos preenchidos
            return; //se não estiverem todo preenchidos vai parar o método "gravar"
        }
        int codigo = produto.getCodigo();
        produto.setCodigo(Integer.parseInt(txtCodigo.getText())); //converte o texto em INT e grava no objeto Produto
        produto.setDescricao(txtDescricao.getText());
        produto.setQtde(Double.parseDouble(txtQuantidade.getText()));
        produto.setValorUnitario(Double.parseDouble(txtValor.getText()));
        if (inserindo) { //verifica se está criando novo ou alterando ja existente
            Repositorio.adicionar(produto);
            produto = Repositorio.localizarProduto(produto.getCodigo());
            preenchercampos();
        }else{
            Repositorio.updateProduto(produto,codigo);
        }
        ativacaoCampos(false); //desabilita os campos após a garvação
        
    }//GEN-LAST:event_gravar

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        if (inserindo) {
            produto = null;
            limparCampos();
        } else {
            preenchercampos();
        }
        ativacaoCampos(false);
    }//GEN-LAST:event_cancelar

    private void alterar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar
        // TODO add your handling code here:
        if(produto != null){
            inserindo = false;
            ativacaoCampos(true);
            txtCodigo.setEnabled(inserindo);
            txtDescricao.requestFocus();
        }
    }//GEN-LAST:event_alterar

    private void excluir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir
        // TODO add your handling code here:
        if(produto != null){
            if(JOptionPane.showConfirmDialog(this, "Tem certeza?","Excluir produto",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String query = "DELETE FROM `produto` WHERE `codigo`=\""+produto.getCodigo()+"\"";
                Repositorio.executaSQlQuery(query);
                Repositorio.remover(produto);
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                produto = null;
                limparCampos();
                ativarBotoes();
            }
        }
    }//GEN-LAST:event_excluir

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        // TODO add your handling code here:
        Jbuscaproduto form = new Jbuscaproduto(this,true);
        form.setVisible(true);
        produto = form.getProduto() != null ? form.getProduto() : produto;
        preenchercampos();
        ativarBotoes();        
    }//GEN-LAST:event_buscar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
